version: "3.4"

services:
  backend:
    container_name: mtauksync_backend
    env_file: .env
    environment:
      - DEBUGPY=${DEBUGPY}
    user: ${CURRENT_UID}
    build:
      context: .
      args:
        - DEBUG=${DEBUG}
      target: deploy
    restart: on-failure
    volumes:
      - ./static:/app/static/
      - .:/app/
    networks:
      # proxy:
      private_network:
        ipv4_address: 172.16.0.8

  backend-dev:
    container_name: mtauksync_backend_dev
    env_file: .env
    environment:
      - DEBUGPY=${DEBUGPY}
    user: ${CURRENT_UID}
    build:
      context: .
      args:
        - DEBUG=${DEBUG}
      target: deploy
    restart: on-failure
    volumes:
      - .:/app/
    ports:
      - 5678:5678
      - 8000:8000
    networks:
      private_network:
        ipv4_address: 172.16.0.5

  postgres:
    container_name: mtauksync_postgres
    env_file: .env
    image: postgres:12.3-alpine
    restart: on-failure
    volumes:
      - mtauksync_db_data:/var/lib/postgresql/data
    networks:
      private_network:
        ipv4_address: 172.16.0.6

  qcluster:
    image: mtauksync_backend
    container_name: mtauksync_qcluster
    env_file: .env
    user: ${CURRENT_UID}
    volumes:
      - ./backend:/app/
      - ./static:/app/static
    restart: on-failure
    entrypoint: python3
    command: ./manage.py qcluster
    depends_on:
      - backend
      - postgres
    networks:
      private_network:
        ipv4_address: 172.16.0.7

  qcluster-dev:
    image: mtauksync_backend-dev
    container_name: mtauksync_qcluster_dev
    env_file: .env
    user: ${CURRENT_UID}
    volumes:
      - ./backend:/app/
      - ./static:/app/static
    restart: on-failure
    entrypoint: python3
    command: ./manage.py qcluster
    depends_on:
      - postgres
    networks:
      private_network:
        ipv4_address: 172.16.0.7

networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/16

volumes:
  mtauksync_db_data:
    external: true
